create database QLSOTIETKIEM;
use QLSOTIETKIEM;
CREATE TABLE SOTIETKIEM
(
    MASOTIETKIEM NVARCHAR(15) PRIMARY KEY,
    MAKHACHHANG NVARCHAR(15),
    SODU INT(30),
    MALOAITIETKIEM NVARCHAR(3),
    NGAYMOSO DATETIME,
    TINHTRANG NVARCHAR(10)
);

CREATE TABLE LOAITIETKIEM
(
    MALOAITIETKIEM NVARCHAR(3) PRIMARY KEY ,
    TENLOAITIETKIEM NVARCHAR(15),
    LAISUAT INT(5),
    SONGAYDUOCRUTTIEN INT(5)
);

CREATE TABLE KHACHHANG
(
    MAKHACHHANG NVARCHAR(15) PRIMARY KEY ,
    TENKHACHHANG NVARCHAR(30),
    DIACHI NVARCHAR(50),
    CMND INT(15)

);

CREATE TABLE PHIEUGUITIEN
(
    MAPHIEUGUITIEN NVARCHAR(15) PRIMARY KEY,
    MASOTIETKIEM NVARCHAR(15),
    MAKHACHHANG NVARCHAR(15),
    NGAYGUI DATETIME,
    SOTIENGUI INT(20)
);

CREATE TABLE PHIEURUTTIEN
(
    MAPHIEURUTTIEN NVARCHAR(15) PRIMARY KEY,
    MASOTIETKIEM NVARCHAR(15),
    MAKHACHHANG NVARCHAR(15),
    NGAYRUT DATETIME,
    SOTIENRUT INT(20)
);
CREATE TABLE DANHSACHSOTIETKIEM
(
    MADS NVARCHAR(15),
    MASOTIETKIEM NVARCHAR(15),
    MALOAITIETKIEM NVARCHAR(3),
    MAKHACHHANG NVARCHAR(15)
);

CREATE TABLE BAOCAODOANHSONGAY
(
    MABAOCAODOANHSO NVARCHAR(15) PRIMARY KEY,
    NGAY DATE,
    MALOAITIETKIEM NVARCHAR(3),
    TONGTHU INT,
    TONGCHI INT
);

CREATE TABLE BAOCAOMODONGSOTHANG
(
    MABAOCAOMDTHANG NVARCHAR(15),
    MALOAITIETKIEM NVARCHAR(3),
    NGAYTHANG DATE,
    SOMO INT(10),
    SODONG INT(10)
);


ALTER TABLE SOTIETKIEM ADD FOREIGN KEY (MALOAITIETKIEM) REFERENCES LOAITIETKIEM(MALOAITIETKIEM);
ALTER TABLE SOTIETKIEM ADD FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG);
ALTER TABLE PHIEUGUITIEN ADD FOREIGN KEY (MASOTIETKIEM) REFERENCES SOTIETKIEM (MASOTIETKIEM);
ALTER TABLE PHIEUGUITIEN ADD FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG);
ALTER TABLE PHIEURUTTIEN ADD FOREIGN KEY (MASOTIETKIEM) REFERENCES SOTIETKIEM (MASOTIETKIEM);
ALTER TABLE PHIEURUTTIEN ADD FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG);
ALTER TABLE DANHSACHSOTIETKIEM ADD CONSTRAINT DS_ID PRIMARY KEY (MADS,MASOTIETKIEM);
ALTER TABLE DANHSACHSOTIETKIEM ADD FOREIGN KEY (MASOTIETKIEM) REFERENCES SOTIETKIEM(MASOTIETKIEM);
ALTER TABLE BAOCAODOANHSONGAY ADD FOREIGN KEY (MALOAITIETKIEM) REFERENCES LOAITIETKIEM(MALOAITIETKIEM);
ALTER TABLE BAOCAOMODONGSOTHANG ADD FOREIGN KEY (MALOAITIETKIEM) REFERENCES LOAITIETKIEM(MALOAITIETKIEM);
ALTER TABLE LOAITIETKIEM ADD CONSTRAINT L_TENLOAI CHECK ( TENLOAITIETKIEM = 'khong ky han' OR TENLOAITIETKIEM = '3 thang' OR TENLOAITIETKIEM = '6 thang');
ALTER TABLE PHIEUGUITIEN ADD CONSTRAINT P_TIENGUI CHECK ( SOTIENGUI >= 100000 );
ALTER TABLE SOTIETKIEM ADD CONSTRAINT SO_CHECK CHECK ( SODU > 0 );
